# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true


# Move the directory to the second line
# format = '$all$directory$character'

format = """($all$package\n)\
($git_branch\n)\
($git_commit$git_state$git_metrics$git_status\n)\
($sudo$directory\n)\
$character"""

[line_break]
disabled = true

[git_branch]
#symbol = ' '
symbol = 'branch'
style="bold red"
# format='on [$symbol[$branch](:$remote_branch)]($style) '
format='[$symbol:$branch(:$remote_branch)]($style) '
# ~/.config/starship.toml
[git_status]
format     = '([$ahead_behind$typechanged$modified$conflicted$stashed$deleted$renamed$staged$untracked]($style))'
style      = "green"
conflicted = '\[conflicted ${count}\]'
ahead      = '\[ahead ${count}\]'
behind     = '\[behind ${count}\]'
diverged   = 'diverged ⇕⇡${ahead_count}⇣${behind_count} '
up_to_date = '\[up to date\] '
untracked  = '\[untracked ${count}\]'
stashed    = '\[untracked ${count}\]'
modified   = '\[modified ${count}\]'
staged     = '\[staged ${count}\]'
renamed    = '\[renamed ${count}\]'
deleted    = '\[deleted ${count}\]'

[directory]
use_logical_path          = true
truncation_length         = 30
disabled                  = false
fish_style_pwd_dir_length = 30

[rust]
symbol = 'Rust  '
[golang]
symbol = 'GO  '
[python]
symbol = 'Python  '
[nodejs]
symbol = 'Node  '

[sudo]
format   = '[$symbol]($style)'
style    = 'green'
symbol   = 'sudo '
disabled = false
#symbol = '󰣇 '
#symbol = 'ˢᵘᵈᵒ '

[character]
format         = '$symbol '
success_symbol = '[](bold green)'
error_symbol   = """[](bold red)"""

[package]
format = '[version $version](green) '
