setw -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
# Mouse Mode
set -g mouse on

# 'vimpostor/vim-tpipeline'
set -g focus-events on
set -g status-style bg=default
set -g status-left '#(cat #{socket_path}-\#{session_id}-vimbridge 2>/dev/null)'
set -g status-left-length 99
set -g status-right '#(cat #{socket_path}-\#{session_id}-vimbridge-R 2>/dev/null)'
set -g status-right-length 99
set -g status-justify absolute-centre

set -g extended-keys on
set -g extended-keys-format csi-u
set -as terminal-features 'alacritty*:extkeys'
# move tmux line to the top
set -g status-position top

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'christoomey/vim-tmux-navigator'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

set -g base-index 1
set -g pane-base-index 1
set -g window-status-current-style bg=black,fg=white,bold
set -g window-status-current-format ' #I:#W '
set -g window-status-format ' #I:#W '
set -g window-status-separator ''

# Add rounded-ish visual separation
set -g window-status-current-format '#[fg=white,bg=black] #I #[fg=white,bg=black]#W '
set -g window-status-format '#[fg=white,bg=black] #I #[fg=grey,bg=black]#W '
